# Generated by Django 5.1.3 on 2024-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Viagem')),
                ('descricao', models.TextField(verbose_name='Descrição da Viagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_viagens/', verbose_name='Imagem da Viagem')),
                ('data_disponibilidade', models.DateField(blank=True, null=True, verbose_name='Data de Disponibilidade')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['titulo'],
            },
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='maior_pontuacao',
        ),
    ]
