# Generated by Django 5.1.1 on 2024-12-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagens',
            name='pais',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='app.pais', verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='fotos_perfil/'),
        ),
    ]
