# Generated by Django 5.1.1 on 2024-12-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_viagens_pais_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagens',
            name='pais',
        ),
    ]
