# Generated by Django 5.1.4 on 2024-12-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='UF',
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='app.pais', verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Cidade'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do País'),
        ),
    ]
