# Generated by Django 5.1.4 on 2024-12-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pais_options_remove_cidade_uf_cidade_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='pais',
        ),
        migrations.AddField(
            model_name='viagens',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='viagens',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais', verbose_name='País'),
        ),
    ]
