# Generated by Django 5.1.1 on 2024-12-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_viagens_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagens',
            name='pais',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='app.pais', verbose_name='País'),
            preserve_default=False,
        ),
    ]
