# Generated by Django 5.1.4 on 2024-12-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_usuarios_cidade_remove_usuarios_pais_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
