# Generated by Django 5.1.4 on 2024-12-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoViagem',
        ),
    ]
