# Generated by Django 5.1.4 on 2024-12-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_tipoviagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('preco_por_noite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('categoria', models.CharField(choices=[('economico', 'Econômico'), ('luxo', 'Luxo'), ('medio', 'Médio')], max_length=100)),
            ],
        ),
    ]
