# Generated by Django 5.1.4 on 2024-12-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_viagens_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='preco_por_noite',
        ),
    ]
